name: Build KPTools & Patch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build xxd cmake make g++

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28
          add-to-path: true

      - name: Set NDK environment variables
        run: |
          echo "NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          echo "ANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Run build.sh
        run: ./build.sh

      - name: Upload patch_android
        uses: actions/upload-artifact@v4
        with:
          name: patch_android
          path: patch_android/

      - name: Upload patch_linux
        uses: actions/upload-artifact@v4
        with:
          name: patch_linux
          path: patch_linux/
